rbcar:
  left_front_shock_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: left_front_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}
  
  left_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    
  #traction
  left_front_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: left_front_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
     
  right_front_shock_controller:
    type: effort_controllers/JointEffortController
    joint: right_front_shock
    pid: {p: 500.0, i: 10.0, d: 500.0}

  right_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    
  #traction
  right_front_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: right_front_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}

  left_rear_shock_controller:
    type: effort_controllers/JointEffortController
    joint: left_rear_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}

  # traction
  left_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: left_rear_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
    
  right_rear_shock_controller:
    type: effort_controllers/JointEffortController
    joint: right_rear_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}

  # traction
  right_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: right_rear_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
        
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
